action_dim: 24
batch_size: 64
csv_root: trajectories
d_model: 64
device: cuda
dropout: 0.1
eval_every: 1000
gamma: 0.99
gradient_clip_norm: 1.0
lr: 0.0003
max_iters: 50000
n_heads: 8
n_layers: 8
n_positions: 200
save_every: 1000
seed: 42
state_dim: 348
use_qvalues: false
warmup_steps: 4000
window_K: 30
